### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by JrJensen** [adventurerok/Colony-Wars#1]
# I have a problem :( 
## 2. If I execute a command, always comes this error message:
**org.bukkit.command.CommandException: Unhandled exception executing command 'cw' in plugin ColonyWars v2.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
	at com.ithinkrok.cw.CWPlugin.onCommand(CWPlugin.java:51) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	... 15 more**

## Hope you can fix it! Else the plugin will not work!!!

**Comment by adventurerok** [comment]
I have uploaded the maps and schematics to my website: https://files.ithinkrok.com/cw_resources.zip
Running the plugin with the maps and schematics installed should hopefully fix the second issue

**Comment by JrJensen** [comment]
### It still does not work :( Here is the errormessage:

java.lang.RuntimeException: Maps directory does not exist!
	at com.ithinkrok.minigames.Game.reloadMaps(Game.java:277) ~[?:?]
	at com.ithinkrok.minigames.Game.reloadConfig(Game.java:186) ~[?:?]
	at com.ithinkrok.cw.CWPlugin.onEnable(CWPlugin.java:27) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]

The maps are in my "mainfolder" and the shematics in the colonywars folder.
Hope you can help me again?
