### ISSUE TITLE
Worlds/Maps are not detected

### ISSUE THREAD

**Issue by JrJensen** [adventurerok/Colony-Wars#2]
### I did everything what you had written, but it still does not work. Error message:

**java.lang.RuntimeException: Maps directory does not exist!
	at com.ithinkrok.minigames.Game.reloadMaps(Game.java:277) ~[?:?]
	at com.ithinkrok.minigames.Game.reloadConfig(Game.java:186) ~[?:?]
	at com.ithinkrok.cw.CWPlugin.onEnable(CWPlugin.java:27) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.Bukkit.reload(Bukkit.java:535) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [MinecraftServer.jar:git-Spigot-5f38d38-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]**

### Hope you can help me again?

**Comment by adventurerok** [comment]
Try creating a directory called "maps" in the "plugins/ColonyWars" folder. If this doesn't work copy the map config files from https://github.com/adventurerok/Colony-Wars/tree/master/src/main/resources/maps into that folder.
